### ISSUE TITLE
Making the App Responsive and Look Good on Mobile Devices

### ISSUE THREAD

**Issue by MarcoMorawec** [colinrubbert/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by colinrubbert** [comment]
I knew I was forgetting something. I'll definitely change that when I get
home after work. This definitely isn't the first time I forgot it, I'm
going to have to hard code that into my brain.

I'm setting up a document sheet to add all these step reminders that I
forget frequently. Thanks for the tip.

**Comment by MarcoMorawec** [comment]
Sounds good. 

Once you're done, include a link to the exact commit where you made the code change so I can give you a quick thumbs up.

PS. Cheat/Reminder sheets are the way to go :)

**Comment by colinrubbert** [comment]
Add the viewport meta tag into the application and it's working good on mobile now, tested it both locally and on heroku. I'll have to remember to not always use the desktop browser resize cheater method to check breakpoints and mobile responsiveness on final product. 

Here's the link to the commit:
https://github.com/colinrubbert/splurty/commit/2093f2194aef78f9f9833f478d3d07833efd960c

**Comment by MarcoMorawec** [comment]
:+1: @colinrubbert 

Make sure you close the issue, now that you're done with it :)

**Comment by colinrubbert** [comment]
Thanks Marco, I will close the issue.
